### ISSUE TITLE
Live example broken?

### ISSUE THREAD

**Issue by jesslawnz** [ivosdc/svelte-generic-crud-table#20]
On the live example, the create item button makes an item that cannot be edited.

Also, when deleting some items, the wrong list item is deleted. 
I haven't installed and tested yet. Will update if I find the root cause

**Comment by ivosdc** [comment]
I looked for the example and did some corrections. By now everything seems to be ok for me.
Create and edit work fine.

Btw. the example shows the webcomponent with a minimal setup, so it's just an example ;) :
The used create and other operations can easily be seen here: https://ivosdc.github.io/svelte-generic-crud-table/crud-table-config-html.js

The idea of the crud-table is to dispatch events for the options "create", "delete", "edit" and "detail" so you can do further operations with the data. E.g. open a separate create/edit-page, implement your own sort-algorithm, do database or api operations... 

I use it to implement in a fast way a DTOs from the backend. The corresponding api-calls can easily be added, especially in svelte  :)
