### ISSUE TITLE
More stripped down example?

### ISSUE THREAD

**Issue by melMass** [ivosdc/svelte-generic-crud-table#24]
Hi,

I'm trying to use this component without sapper without luck.
Is there a sample without using routes and sapper? 
From the sample (replacing all `get` `post` with svelte logic) `myData` is properly updated but not the table.

Thanks

**Comment by melMass** [comment]
I guess it has something to do with ID's or something like that

**Comment by ivosdc** [comment]
Hello,
there is an implementation (Svelte only)
https://github.com/ivosdc/svelte-generic-table-pager/blob/master/src/GenericTablePager.svelte

Hopefully this helps as a blueprint.
